# Generated by Django 5.2.6 on 2025-09-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('grave', 'Grave'), ('alto', 'Alto'), ('medio', 'Mediano')], default='medio', max_length=10),
        ),
    ]
