# Generated by Django 5.2.6 on 2025-10-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('org_admin', 'Organization Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
