# Generated by Django 5.2.6 on 2025-10-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_device_name_per_org'),
        ),
    ]
