# Generated by Django 5.2.6 on 2025-10-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_device_options_alter_measurement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
