# Generated by Django 5.2.6 on 2025-10-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alert_acknowledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ORG_ADMIN', 'Org Admin'), ('VERIFIER', 'Verifier'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
