# Generated by Django 5.2.6 on 2025-11-08 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='core.category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='core.zone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='core.organization'),
        ),
    ]
